### ISSUE TITLE
Need to update Cucumber examples to be compatible for execution from TP platform

### ISSUE THREAD

**Issue by gil-testproject** [testproject-io/java-opensdk#108]
Currently, the cucumber examples will not work if you upload them because the features files are not embeded resources.
You need to make the features embeded resources and update the code to use them from the resources instead from local folder

For example:
```java
@RunWith(Cucumber.class)
@CucumberOptions(features = "classpath:features/",
        glue = "cucumber.stepdefinitions",
        plugin = "io.testproject.sdk.internal.reporting.extensions.cucumber.CucumberReporter")
```

While features is under resources

**Comment by DavidG8168** [comment]
#109
