### ISSUE TITLE
Give reporting queue more time to send all the reports

### ISSUE THREAD

**Issue by s-glatshtein** [testproject-io/java-opensdk#138]
Today, we allow only 10 seconds on process stop to send all the reports. Sometimes there's a lot of reports or a very slow connection to a remote machine that is causing this to be insufficient. We should do the following:

1. Increate the time we wait to 10 minutes.
2. While waiting, we should notify the user every few seconds that there are X remaining reports to be sent.

**Comment by DavidG8168** [comment]
#137
