### ISSUE TITLE
In the Test Project report we are seeing : instead of element names we seeing their Xpath expressions being recorded

### ISSUE THREAD

**Issue by VinothMessi** [testproject-io/java-opensdk#59]
![image](https://user-images.githubusercontent.com/34208574/102324399-d0cb3a00-3fa7-11eb-9714-d732d33474ed.png)

In the Test Project report : Instead of element names we seeing their Xpath expressions

![image](https://user-images.githubusercontent.com/34208574/102324501-f3f5e980-3fa7-11eb-8b23-35e8f7bc13ec.png)

**Comment by DavidG8168** [comment]
Hey @VinothMessi ,

This is the expected behavior.

Elements will appear in the reports on TestProject with the locator value that was used to find them on the application.

**Comment by VinothMessi** [comment]
Actually my bad, this was intended as an enhancement rather than an issue,
seeing locators in reports looks odd. As the reports will be sent over
accords the management

**Comment by mstrelex** [comment]
@VinothMessi Indeed this could be very nice to see the field name instead of the locator, labeling as an enhancement.

**Comment by DavidG8168** [comment]
Addressed in https://github.com/testproject-io/csharp-opensdk/issues/155
